version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: flashsale_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=flashsale_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - flashsale_net

  redis:
    image: redis:7-alpine
    container_name: flashsale_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - flashsale_net

networks:
  flashsale_net:
    driver: bridge

volumes:
  pgdata: